name: "ezTikTok"
mode: "dev"
port: 8081
version: "v0.1.2"
start_time: "2023-03-11"
machine_id: "1"
log:
  level: "debug"
  filename: "ezTikTok.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "172.17.130.204"
  port: 3307
  user: "root"
  password: "123456"
  db_name: "eztt"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100