basePath: /api/v1/
host: localhost:8081
info:
  contact:
    email: support@swagger.io
    name: Lemon
    url: http://www.swagger.io/support
  description: 博客论坛
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Blog
  version: 0.1.0
paths: {}
swagger: "2.0"
